"""
Local NIMS configuration bridge.

This module prevents all NIMS files from importing global project config
directly and gives us one stable import point.
"""

from soulsync.config import (
    NIMS_ENABLED,
    NIMS_REQUIRE_APPROVED_MODEL,
    NIMS_DEBUG_PANEL,
    NIMS_DEFAULT_PROVIDER,
    NIMS_DEFAULT_MODEL_ID,
    NIMS_MIN_APPROVAL_SCORE,
    NIMS_MAX_SAFETY_FAILURES,
    NIMS_MAX_TOPIC_FAILURES,
    NIMS_MAX_LITERALNESS_FAILURES,
    NIMS_TOPIC_EMBEDDING_DIM,
    NIMS_TOPIC_HIGH_ADHERENCE_THRESHOLD,
    NIMS_TOPIC_MEDIUM_ADHERENCE_THRESHOLD,
    NIMS_TOPIC_LOW_ADHERENCE_THRESHOLD,
    NIMS_TOPIC_MAX_LEDGER_TERMS,
)

__all__ = [
    "NIMS_ENABLED",
    "NIMS_REQUIRE_APPROVED_MODEL",
    "NIMS_DEBUG_PANEL",
    "NIMS_DEFAULT_PROVIDER",
    "NIMS_DEFAULT_MODEL_ID",
    "NIMS_MIN_APPROVAL_SCORE",
    "NIMS_MAX_SAFETY_FAILURES",
    "NIMS_MAX_TOPIC_FAILURES",
    "NIMS_MAX_LITERALNESS_FAILURES",
    "NIMS_TOPIC_EMBEDDING_DIM",
    "NIMS_TOPIC_HIGH_ADHERENCE_THRESHOLD",
    "NIMS_TOPIC_MEDIUM_ADHERENCE_THRESHOLD",
    "NIMS_TOPIC_LOW_ADHERENCE_THRESHOLD",
    "NIMS_TOPIC_MAX_LEDGER_TERMS",
]

